# Generated by Django 3.1 on 2020-08-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to='menu_image')),
                ('caption', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star', models.FloatField()),
                ('notification', models.TextField()),
                ('opening_hours', models.CharField(max_length=20)),
                ('tel_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('min_order', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=20)),
                ('company_registration_number', models.CharField(max_length=20)),
                ('origin_information', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_image')),
                ('delivery_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_charge', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_group', to='restaurants.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField()),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='restaurants.optiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_group', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.menugroup'),
        ),
    ]
