# Generated by Django 3.1 on 2020-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star', models.FloatField()),
                ('notification', models.TextField()),
                ('opening_hours', models.CharField(max_length=20)),
                ('tel_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('min_order', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=20)),
                ('company_registration_number', models.CharField(max_length=20)),
                ('origin_information', models.CharField(max_length=255)),
            ],
        ),
    ]
