# Generated by Django 3.1 on 2020-09-17 07:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to='menu_image')),
                ('caption', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('is_photomenu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('star', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notification', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('tel_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('min_order_price', models.PositiveIntegerField()),
                ('payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('business_name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(max_length=255)),
                ('origin_information', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_image')),
                ('delivery_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_time', models.CharField(max_length=255)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='restaurant_back_image')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1인분주문', 'One Serving'), ('프랜차이즈', 'Franchise'), ('치킨', 'Chicken'), ('피자양식', 'Pizza'), ('중식', 'Chinese'), ('한식', 'Korean'), ('일식돈까스', 'Japanese'), ('족발보쌈', 'Jokbal'), ('야식', 'Midnight'), ('분식', 'Snack'), ('카페디저트', 'Cafe'), ('편의점', 'Convenience'), ('테이크아웃', 'Takeout')], max_length=20), size=None)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_group', to='restaurants.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='restaurants.optiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_group', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.menugroup'),
        ),
    ]
