# Generated by Django 3.1 on 2020-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tel_number',
            field=models.CharField(max_length=40),
        ),
    ]
