# Generated by Django 3.1 on 2020-09-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.PositiveIntegerField(),
        ),
    ]
