# Generated by Django 3.1 on 2020-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='mandatory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
