# Generated by Django 3.1 on 2020-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200903_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
