# Generated by Django 3.1 on 2020-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200920_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='representative_menus',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
