# Generated by Django 3.1 on 2020-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200903_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='payment_method',
            new_name='payment_methods',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
