# Generated by Django 3.1 on 2020-09-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200924_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='amount',
            new_name='average_amount',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='delivery',
            new_name='average_delivery',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='taste',
            new_name='average_taste',
        ),
    ]
