# Generated by Django 3.1 on 2020-09-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200903_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_back_image'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lan',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='log',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
