# Generated by Django 3.1 on 2020-09-16 08:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menu_is_photomenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='min_order',
            new_name='min_order_price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1인분주문', 'One Serving'), ('프랜차이즈', 'Franchise'), ('치킨', 'Chicken'), ('피자양식', 'Pizza'), ('중식', 'Chinese'), ('한식', 'Korean'), ('일식돈까스', 'Japanese'), ('족발보쌈', 'Jokbal'), ('야식', 'Midnight'), ('분식', 'Snack'), ('카페디저트', 'Cafe'), ('편의점', 'Convenience'), ('테이크아웃', 'Takeout')], max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='star',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tel_number',
            field=models.CharField(max_length=20),
        ),
    ]
