# Generated by Django 3.1 on 2020-09-11 07:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200909_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
