# Generated by Django 3.1 on 2020-09-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200903_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lan',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='log',
            new_name='lng',
        ),
    ]
