# Generated by Django 3.1 on 2020-08-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
