# Generated by Django 3.1 on 2020-09-03 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200903_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category_restaurant',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category_Restaurant',
        ),
    ]
