# Generated by Django 3.1 on 2020-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
