# Generated by Django 3.1 on 2020-08-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200827_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.menugroup'),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_group', to='restaurants.restaurant'),
        ),
    ]
