# Generated by Django 3.1 on 2020-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_review_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='review_comment_count',
            new_name='owner_comment_count',
        ),
    ]
