# Generated by Django 3.1 on 2020-10-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20201002_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_discount',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
