# Generated by Django 3.1 on 2020-08-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200827_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='restaurants.optiongroup'),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_group', to='restaurants.menu'),
        ),
    ]
