# Generated by Django 3.1 on 2020-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20201012_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_discount',
            field=models.PositiveIntegerField(),
        ),
    ]
