# Generated by Django 3.1 on 2020-08-28 05:25

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20200828_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=restaurants.models.menu_img_path),
        ),
    ]
