# Generated by Django 3.1 on 2020-08-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20200828_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='menu_img'),
        ),
    ]
