# Generated by Django 3.1 on 2020-08-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20200828_0530'),
        ('restaurants', '0009_auto_20200827_0825'),
    ]

    operations = [
    ]
