version: "3"

services:
  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379

  db:
    image: kartoza/postgis:12.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: yogiyo

volumes:
  postgres-data:
