# Generated by Django 3.1 on 2020-09-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('delivery_requests', models.CharField(default='(없음)', max_length=255)),
                ('payment_method', models.CharField(choices=[('현금', 'Cash'), ('신용카드', 'Creditcard'), ('요기서결제', 'Yogiyo Pay')], max_length=10)),
                ('total_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('order_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_option_group', to='orders.ordermenu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('order_option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_option', to='orders.orderoptiongroup')),
            ],
        ),
    ]
