# Generated by Django 3.1 on 2020-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200903_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoption',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderoptiongroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
