# Generated by Django 3.1 on 2020-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200903_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
