# Generated by Django 3.1 on 2020-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_review_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('접수 대기 중', 'Waiting For Receipt'), ('접수 완료', 'Receipt Complete'), ('배달 중', 'Delivery'), ('배달 완료', 'Delivery Complete')], default='배달 완료', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('현금', 'Cash'), ('신용카드', 'Credit Card'), ('요기서결제', 'Yogiyo Pay')], max_length=10),
        ),
    ]
