# Generated by Django 3.1 on 2020-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200924_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('접수 대기 중', 'Waiting For Receipt'), ('접수 완료', 'Receipt Complete'), ('배달 중', 'Delivery'), ('배달 완료', 'Delivery Complete')], default='접수 대기 중', max_length=10),
        ),
    ]
