# Generated by Django 3.1 on 2020-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
