# Generated by Django 3.1 on 2020-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200924_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', '현금'), ('CREDIT_CARD', '신용카드'), ('YOGIYO_PAY', '요기서결제')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_RECEIPT', '접수 대기 중'), ('RECEIPT_COMPLETE', '접수 완료'), ('DELIVERY', '배달 중'), ('DELIVERY_COMPLETE', '배달 완료')], default='WAITING_FOR_RECEIPT', max_length=20),
        ),
    ]
