# Generated by Django 3.1 on 2020-09-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermenu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoptiongroup',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
