# Generated by Django 3.1 on 2020-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderoptiongroup_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_requests',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
