# Generated by Django 3.1 on 2020-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200909_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_requests',
            field=models.CharField(default='(없음)', max_length=255),
        ),
    ]
