# Generated by Django 3.1 on 2020-08-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
