# Generated by Django 3.1 on 2020-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200920_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_menu',
            field=models.CharField(max_length=100),
        ),
    ]
