# Generated by Django 3.1 on 2020-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200922_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='order_menu',
            new_name='menu_name',
        ),
    ]
