# Generated by Django 3.1 on 2020-09-24 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20200924_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
