# Generated by Django 3.1 on 2020-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20200930_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewComment',
            new_name='OwnerComment',
        ),
    ]
