# Generated by Django 3.1 on 2020-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200924_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
